### PR TITLE
Fix space on end of page name creates two pages, one shadowed #615

### LINKED ISSUE #615: Space on end of page name creates two pages, one shadowed
**What happened**
1. Create a new page using the "Page: From Template" command with a space at the end of the name
image

2. See that two pages are created, but links always point to the page without space at the end
image

3. View on filesystem
image

**What I expected**
- Creating a new page using the "Page: From Template" command with a space at the end of the name should strip the space from the name before creating a page.
- Only the page without a space at the end should be created

### PR DESCRIPTION
**Pull request by fflorent**
## Context

Fixes #615.

## Proposed solution

1. Disallow PUT on filename with filenames surrounded with spaces;
2. If the filename provided on GET is surrounded by spaces, redirect to its trimmed version;
3. In case of required authentication, return a 401 (UNAUTHORIZED) + redirect;

## Other

If you want me to create tests, I would like to know if there already exists files places I can put them in.

### CODE REVIEW

File: common/spaces/http_space_primitives.ts [hunk 1]
```diff
@@ -34,14 +34,18 @@ export class HttpSpacePrimitives implements SpacePrimitives {
...
+        if (result.status === 401) {
+          console.log(
+            "Received unauthorized status and got a redirect via the API so will redirect to URL",
+            result.url,
+          );
+          alert("You are not authenticated, redirecting to login page...");
+          location.href = result.url;
+          throw new Error("Not authenticated");
+        } else {
+          location.href = result.url;
```
Comment (zefhemel) [inline common/spaces/http_space_primitives.ts:46]: Previously it would show an alert in this case, any particular reason why it shouldn't anymore?

File: server/http_server.ts [hunk 2]
```diff
@@ -469,6 +470,7 @@ export class HttpServer {
         const req = c.req;
         const name = req.param("path")!;
         const spaceServer = await this.ensureSpaceServer(req);
+        const mdExt = ".md";
```
Comment (zefhemel) [inline server/http_server.ts:473]: If you introduce constants like this, I'd prefer them at the top level (top of the file, next to `authenticationExpirySeconds`) for instance.

**Review by zefhemel — CHANGES_REQUESTED** [review]

File: common/spaces/http_space_primitives.ts (hunk 1 above)
Comment (fflorent) [reply common/spaces/http_space_primitives.ts:46]: The alert still appears when the reason of the redirection is a `401 - Authentication Required` (line 42) and the server code has been adapted below (in `server/http_server.ts:491`).

File: server/http_server.ts (hunk 2 above)
Comment (fflorent) [reply server/http_server.ts]: Done

File: common/spaces/http_space_primitives.ts (hunk 1 above)
Comment (fflorent) [reply common/spaces/http_space_primitives.ts:46]: @zefhemel Does this answer your question? Or you are still worried about that change?

**Comment by zefhemel** [comment]
Sorry for the delay, this looks good. Thanks!
